environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

install:
  - "%PYTHON%\\Scripts\\pip.exe install -r requirements.txt"
  - "%PYTHON%\\Scripts\\pip.exe install -r requirements-dev.txt"
  - python setup.py install

build: off

test_script:
  - python setup.py test
  - "dir /s /b C:\\projects\\pywoudc\\*.py | findstr /V docs | xargs %PYTHON%\\Scripts\\pep8 --ignore=E402"
  - "dir /s /b C:\\projects\\pywoudc\\*.py | findstr /V docs | xargs %PYTHON%\\Scripts\\pyflakes"
  - sphinx-apidoc -A "Tom Kralidis" -F -o docs pywoudc
  - cd docs && make html
  - cd ..

on_success:
  - coverage run --source pywoudc setup.py test
  - coverage report -m
